### ISSUE TITLE
[BUG] Duration TimeSpan.MaxValue throws

### ISSUE THREAD

**Issue by suhrab** [ZiggyCreatures/FusionCache#124]
Hey Jody. Very little bug. Workaround is very easy. Just for you to know

**Describe the bug**
I want item in cache have no expiration. Setting Duration=TimeSpan.MaxValue throws an exception.
System.ArgumentOutOfRangeException: 'The added or subtracted value results in an un-representable DateTime. (Parameter 'value')'

**To Reproduce**
https://gist.github.com/suhrab/a8b597f647be86c0e1ad6c45a06fc1e2

**Expected behavior**
Setting duration to TimeSpan.MaxValue should not throw. My workaround is to set Duration to 100 years. TimeSpan.FromDays(36_500)

**Versions**
I've encountered this issue on:
- FusionCache 0.19.0
- .NET 7
- Windows 10

**Comment by jodydonetti** [comment]
Hi @suhrab  and thanks for using FusionCache!

Regarding the bug: yep, you are right. One thing I may do is add a check like `if (duration > (DateTimeOffset.MaxValue - now))` and, in that case, just set the duration to `DateTimeOffset.MaxValue`, or some other safe max value.

Also worth thinking about what happens in the SqlServer impl of `IDistributedCache`, since the max value there may also be different: maybe the right **pragmatic** approach would be to define somewhere something like `public static readonly DateTimeOffset MaxExpiration = ...` and use that as a safe value (something like the year 3000 or similar) and normalize input options to that.

Will update you soon, thanks for the tip!

**Comment by jodydonetti** [comment]
Hi @suhrab , I've created [an issue](https://github.com/ZiggyCreatures/FusionCache/issues/126) to track the design and development of this, plus some extra niceties.

**Comment by suhrab** [comment]
Hey, Jody. SetDurationInfinite() + Jittering looks good. Confirmed 👍 

> the expiration will not be literally "infinite", but it will be set to <see cref="DateTimeOffset.MaxValue"/> which in turn is Dec 31st 9999 which, I mean, c'mon. If that time will come and you'll have some problems feel free to try and contact me :-)
I certainly will 😅

**Comment by jodydonetti** [comment]
> Hey, Jody. SetDurationInfinite() + Jittering looks good. Confirmed 👍 

Great, thanks for checking it!

> I certainly will 😅

Ahahah ok, we'll have a beer then 😬

**Comment by jodydonetti** [comment]
Hi all, I just release [v0.20.0-preview2](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.20.0-preview2) 🎉

Unless some problems will came up this week, the next weekend I'll release the final **v0.20.0**.

**Comment by jodydonetti** [comment]
Hi everyone, I've finally released the new [v0.20.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.20.0) 🎉
