### ISSUE TITLE
[FEATURE] Method to remove multiple keys at once

### ISSUE THREAD

**Issue by celluj34** [ZiggyCreatures/FusionCache#141]
## Problem
I would like to be able to remove multiple keys at once.

## Solution
Currently, I have to loop over a list and call `.Remove` for each.

## Alternatives
n/a

## Additional context
n/a

**Comment by jodydonetti** [comment]
Hi @celluj34 , FusionCache has been designed to use the 2 common caching abstractions in .NET: `IMemoryCache` and `IDistributedCache`.

This decision has pros, like the fact that any available impl (mostly for `IDistributedCache` of course) could be easily used, without anyone having to explicitly create an implementation of, say, a custom `IFusionCacheLayer` or something like that. It has also cons, like being limited to the features defined in those 2 abstractions.

Since they do not have a way to do multi-key operations, the same is not possible in FusionCache.

Of course it would be possible to add those methods so that, internaly, they just do what you did (`foreach` + `Remove(...)`) but:
1) that is very easy to do as an ext method in any project of our own, if so desired
2) adding that to the overall API surface area would imply a promise to the users that FusionCache does that in some native way, which is not the case

Hope this helps.

**Comment by celluj34** [comment]
I understand, thank you 🥲

**Comment by davidhenley** [comment]
@jodydonetti Can we do the same, just by grabbing the IMemoryCache and calling clear on it or would that break FusionCache?

Could you expose the IMemoryCache layer so that we may call Clear on it?

**Comment by jodydonetti** [comment]
> @jodydonetti Can we do the same, just by grabbing the IMemoryCache and calling Compact on it or would that break FusionCache?

No, it would not break FusionCache but also I don't see how `Compact()` would remove multiple cache entries at once as per your original request, unless you meant not "specific" entries by ids, but only "some" of them.

> Could you expose the MemoryCacheAccessor so that we may call Compact on it or should we just do it ourselves?

You can already do that, just the other way around: initialize FusionCache by passing it a `MemoryCache` instance you create, and keep it around: then call any method you want on it, whenever you want (including `Compact()`).
FusionCache respects the api surface area and doesn't act on hidden props or anything.

> I just want to be able to clear the entire cache programatically.

Watch out for a couple of things though:
1) entries with `NeverRemove` priority will not be removed per the official doc
2) if you are using FusionCache with a 2nd level, that would of course not be cleared

Hope this helps!

**Comment by davidhenley** [comment]
Sorry I meant `Clear()` not `Compact()`

**Comment by davidhenley** [comment]
Ah, I think this is correct:

services.AddFusionCache().WithMemoryCache(provider => provider.GetRequiredService<IMemoryCache>())

**Comment by jodydonetti** [comment]
> Hey @jodydonetti, I was wondering if you could help me one last time.

Hey, no worries! If I can be of help I'm glad 😊
And sorry for the delay, quite a busy week!

> I understand what I'm trying to do: "initialize FusionCache by passing it a MemoryCache instance you create" but my head is a bit fuzzy today, and I want to make sure it's done correctly.

No problem, here's [a sample](https://gist.github.com/jodydonetti/ef53f8126430a03713c8e78d713f6df2) I hope can clear things up.

Normally caches (not just FusionCache, but anyone) are registered as a _singleton_: this is done because otherwise each time you would get a new (empty) instance, defeating the purpose of having a shared state where to put shared data.

When you do `AddFusionCache()` though, by default a new `MemoryCache` instance is created on the fly for FusionCache to use, instead of using the global singleton instance of `IMemoryCache`.

But why is that?

This has been done because with FusionCache you can use [multiple named caches](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/NamedCaches.md) and in that case, if every named instance use the same `MemoryCache` singleton instance, you may end up with cache key collisions: because of this you have to specific if you want it to use the DI-provided global singleton instance.

So, to use the global singleton instance, you have to do what you suggested:

```csharp
services.AddFusionCache().WithMemoryCache(provider => provider.GetRequiredService<IMemoryCache>());
```

or, in a more convenient way, by using the provided `WithRegisteredMemoryCache()` method, like this:

```csharp
services.AddFusionCache().WithRegisteredMemoryCache();
```

where **"Registered"** is the key part to look out for.

As shown in the sample, a different way may be to directly create a `MemoryCache` instance, and simply pass that to the builder, like this:

```csharp
var memoryCache = new MemoryCache(new MemoryCacheOptions());
services.AddFusionCache().WithMemoryCache(memoryCache);
```

In this way you would directly have an instance of `MemoryCache` (the concrete class) instead of having to get an `IMemoryCache` (the interface) from the DI container, and then having to cast it to `MemoryCache` to access the `Clear()` method (which is on the class and not on the interface).

> I'm a bit confused on how the FusionCacheBuilder uses the IMemoryCache interface.
The builder can accept an `IMemoryCache` instance directly or a lambda that would build it or it can be told to just use what's in the DI container.

> I want to grab IMemoryCache and call:
> 
> ```cs
> if (IMemoryCache is MemoryCache internalCache) internalCache.Clear();
> ```
> 
> to remove all local cache. (Just for development purposes) but this doesn't work.
> 
> The cache is still around in FusionCache.

Look at the sample gist I prepared, and look at the output I got by running it.

![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/7dd165ac-1ce7-40ea-9271-57de89cedd12)

Try to run it yourself and let me know if it works.

> Again, thank you so much for your help.

You're welcome, I hope I'm being somewhat useful.

> Your library is amazing and I'm hoping to learn more about caching.

Thanks, I'm happy you're liking FusionCache!

**Comment by davidhenley** [comment]
@jodydonetti Dude, thank you so much!

This is such a great explanation, and helped me reason about things much better. 

Thank you for your time in writing all this up!

**Comment by jodydonetti** [comment]
Happy to oblige 😎

![image](https://github.com/ZiggyCreatures/FusionCache/assets/1010086/022e8e0c-a0b4-461b-bb87-4fb2b3f17b64)
