### ISSUE TITLE
[FEATURE] Disposing evicted items

### ISSUE THREAD

**Issue by giulianob** [ZiggyCreatures/FusionCache#169]
## Problem
I'm migrating from `IMemoryCache` and I was able to call `Dispose` on the evicted items by passing the item to the `PostEvictionCallback`, for example:
```
  new MemoryCacheEntryOptions()
      .RegisterPostEvictionCallback(
          callback: (key, value, reason, state) => { ((IDisposable)state).Dispose(); },
          state: item);
```

## Solution
I'd like the ability to either having FusionCache auto call `Dispose` on evicted items or a way to pass the evicted item to the `Eviction` handler.

**Comment by jodydonetti** [comment]
Hi @giulianob and thanks for using FusionCache!

A couple of points.

I may add a `FusionCacheEntryOption` to auto-dispose a value when evicted, so that you may have granular control per each cache entry. Of course as always you may then set this in the `DefaultEntryOptions` once and it will be used as a default for all entries.
Sounds good?

What do you think should happen when a value is being set (either by calling a `Set()`, `GetOrSet()` or because of a remote notification from the backplane, etc) and there's an override? I'm not 100% sure `IMemoryCache` always considers this an eviction even though [here](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.memory.evictionreason) there's a `Replaced` value (anyway I'll check and do some tests), so I would like to know if in this case you would also like to dispose, since the old value is being overwritten.
Ofcourse in that case I should also probably check for the fact that the new value is different from the old one, otherwise a piece of code like this:

```csharp
var myDisposable = new MyDisposable();

cache.Set("foo", myDisposable);
cache.Set("foo", myDisposable);
```

would end up disposing the very object we are about to set.

Let me know what you think, thanks.

**Comment by jodydonetti** [comment]
In the meantime I was also thinking about this: as we know a memory cache stores live object references, therefore when you get something from the cache you are using exactly the same instance.

This means that if you get something from the cache and then it gets disposed, you'll end up working on a disposed object, with all the problems this will create.

A practical example:

```csharp
var myDisposable = new MyDisposable();

cache.Set("foo", myDisposable, TimeSpan.FromSeconds(2));

var foo = cache.GetOrDefault<MyDisposable>("foo");

// 2 SEC LATER...

if (foo is not null) {
  // THIS WILL PROBABLY THROW AN ObjectDisposedException
  foo.Whatever();
}
```

What do you think?

**Comment by giulianob** [comment]
In my scenario, I am making sure to set the duration longer than the amount of time the object can be referenced (the request timeout in my case). You do need to be careful. I am storing objects that must be disposed to free up resources rather than waiting for GC to occur.

**Comment by giulianob** [comment]
@jodydonetti Is there any workaround available to get the item being evicted in the callback?

**Comment by jodydonetti** [comment]
Hi @giulianob , I'm looking into this right now.
I'd like to avoid releasing a new version in a rush, so if I can find a quick temporary workaround I'll tell you right away.
Will update you asap.

**Comment by jodydonetti** [comment]
I think I need to release a new version, there's no other way around it.

I'll try to release it tomorrow night.

**Comment by giulianob** [comment]
Yeah pre-release would be fine. Thanks!

**Comment by jodydonetti** [comment]
Hi all, the [v0.24.0-preview1](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.24.0-preview1) pre-release is out now on Nuget 🎉

NOTE: remember to check the "include prerelease" checkbox in your IDE to see it!

**Comment by jodydonetti** [comment]
Ho @giulianob , did you have time to check this?

Thanks!

**Comment by giulianob** [comment]
Yes, exactly what I needed. Thanks!

**Comment by jodydonetti** [comment]
Awesome, thanks 🥳

Will close this when the non-preview next version will be release.

**Comment by jodydonetti** [comment]
Hi all, the [v0.24.0](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v0.24.0) release is out now on Nuget 🎉
