### ISSUE TITLE
[QUESTION] Read from Replica

### ISSUE THREAD

**Issue by antoniomelotraycorp** [ZiggyCreatures/FusionCache#342]
Hello, I have a redis cluster and i would like to direct reads to the replica node, is it possible to use something like the `CommansFlags.PreferReplica` that is available on StackExchange.Redis ?

**Comment by jodydonetti** [comment]
Hi @antoniomelotraycorp , no that's not possible.

Why?

Because FusionCache can use Redis as a distributed cache via the [`RedisCache`](https://github.com/dotnet/aspnetcore/blob/main/src/Caching/StackExchangeRedis/src/RedisCache.cs) class, which is an `IDistributedCache` implementation based on StackExchange.Redis.
Therefore FusionCache is limited to the options available on that class and its options.

So what I would suggest is to [create an issue](https://github.com/dotnet/aspnetcore/issues) over the ASP.NET repo to allow configurig that (I suppose via some extra options).

Let me know what you think.

Hope this helps.

**Comment by antoniomelotraycorp** [comment]
@jodydonetti Thanks for the reply!
