### ISSUE TITLE
[FEATURE] TrySet api method

### ISSUE THREAD

**Issue by fmendez89** [ZiggyCreatures/FusionCache#79]
Hi @jodydonetti
firstly thanks for your contribution to the community, we have just started to use FusionCache on production and has been working flawesly since then. We are constantly trying to use it in different case scenarios, like the one I'm exposing to you right now. In our case, we are using the backplane with several nodes synchronized with redis.

We are considering using fusion cache as a deduplicator for streaming messages coming from different sources. Right now the best solution we have came was using the two core methods TryGet and Set in a way that it mimics the sliding expiration, but if the same request happens in different nodes with the same key, the set method will be called twice and the deduplicator won't be able to handle correctly that scenario.

```c#
public async Task<bool> IsDuplicated(string deviceName, DateTime timestamp)
{
    var key = LocationCacheKey(deviceName, timestamp);
    var isProcessed = await _cache.TryGetAsync<int>(key);
    if (_logger.IsEnabled(LogLevel.Information))
    {
        if (isProcessed.HasValue)
        {
            _logger.LogInformation("Device {Device} location with timestamp {Timestamp} duplicated, refreshing duration", deviceName, timestamp.ToString("O"));
        }
        else
        {
            _logger.LogInformation("Device {Device} location with timestamp {Timestamp} not duplicated, processing location and setting the cache", deviceName, timestamp.ToString("O"));
        }
    }
    await _cache.SetAsync<int>(key, 1, EntryOptions);
    return isProcessed.HasValue;
}
```
The GetOrSet method won't be a fit to this case because [as per the documentation](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/CacheStampede.md#multiple-nodes), this 'problem' also exists. And we also need the "sliding expiration" we mimic using the Set method.

We have considered using just the StackExchange redis client, but we would lost the in memory cache.
The solution that we would like to have is the one I expose below, using the TrySet method. In that case the value won't be set twice because the TrySet would return false/null and the other nodes will know that is a duplicate.

```c#
public async Task<bool> IsDuplicated(string deviceName, DateTime timestamp)
{
    var key = LocationCacheKey(deviceName, timestamp);
    var isProcessed = await _cache.TryGetAsync<int>(key);
    if (isProcessed.HasValue)
    {
        // Refresh duration
        _logger.LogInformation("Device {Device} location with timestamp {Timestamp} duplicated, refreshing duration", deviceName, timestamp.ToString("O"));
        await _cache.SetAsync<int>(key, 1, EntryOptions);
        return true;
    }
    
    // Try set the key
    var isSet = await _cache.TrySetAsync<int>(key, 1, EntryOptions);
    if (isSet)
    {
        _logger.LogInformation("Device {Device} location with timestamp {Timestamp} not duplicated, processing location and setting the cache", deviceName, timestamp.ToString("O"));
    }
    else
    {
        _logger.LogInformation("Device {Device} location with timestamp {Timestamp} duplicated when trying to set the key", deviceName, timestamp.ToString("O"));
    }
    
    return !isSet;
}
```

I know using just the Redis client would be possible because of the SET command which has the NX option 
``NX -- Only set the key if it does not already exist.`` but, since fusion cache is using IDistributedCache, I believe that won't be easy to fit, but I'm making this proposal so you can consider it. 

Please let me know if you need more context or I can help you.

**Comment by jodydonetti** [comment]
Hi @fmendez89 and thanks for using FusionCache!

> firstly thanks for your contribution to the community, we have just started to use FusionCache on production and has been working flawesly since then. We are constantly trying to use it in different case scenarios

Great! I'm happy you're finding it useful 🎉

I'll try to take a look at this use case and will let you know asap: I'm about to take a break and have my 2 weeks of holidays, but I'll try to answer you before leaving.

**Comment by fmendez89** [comment]
No problem, I'm taking 2 weeks off too, no need to rush. :)

**Comment by jodydonetti** [comment]
Hi @fmendez89 , getting back to this.

If I got this right what you would like is to have a `TrySet` method that would set some data in the cache, but only if that data is not there yet.
I'm certainly open to a new feature, but first I'd like to explore some potential concerns with you.

These are the first things that I'm thinking about:
- since FusionCache is (optionally) multi-level, how should it work when there's only the memory cache?
- in case of 2 levels, the way it works for all other methods (`TryGet`, `Set`, `Delete`, etc) is that it first checks the memory cache, then the distributed one. For this method should it do the same or were you thinking about doing the opposite?
- when talking to the distributed cache, should it wait for the distributed cache to respond, even in case of timeouts or would it be acceptable to use the already existing timeouts?
- as you correctly pointed out, Redis may have a way to implement this but there are other implementations available and since I'm using the standard `IDistributedCache` as the _lingua franca_, that abstraction does not have a method to do that

What do you think? How would you approach these points? Thanks in advanced for participating!

**Comment by jodydonetti** [comment]
I'm closing this since there doesn't seem to be interest.
